import './globals.scss' 
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import  {CSSProperties} from 'react';


const inter = Inter({ subsets: ['latin'] })

export interface MyCustomCSS extends CSSProperties {
  '--interval': number;
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app', 
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const spanArray = new Array(60) 
  console.log(spanArray.map((item, i) => i ), 'asdasd')
  console.log(spanArray, 'spanArray')
 
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='container'>
          <div className='bubbles'>
              <span style={{"--interval": 11} as MyCustomCSS}/>   
              <span style={{"--interval": 12} as MyCustomCSS}/>   
              <span style={{"--interval": 24} as MyCustomCSS}/>   
              <span style={{"--interval": 10} as MyCustomCSS}/>   
              <span style={{"--interval": 14} as MyCustomCSS}/>   
              <span style={{"--interval": 23} as MyCustomCSS}/>   
              <span style={{"--interval": 18} as MyCustomCSS}/>   
              <span style={{"--interval": 16} as MyCustomCSS}/>   
              <span style={{"--interval": 19} as MyCustomCSS}/>   
              <span style={{"--interval": 19} as MyCustomCSS}/>   
              <span style={{"--interval": 20} as MyCustomCSS}/>   
              <span style={{"--interval": 22} as MyCustomCSS}/>   
              <span style={{"--interval": 25} as MyCustomCSS}/>   
              <span style={{"--interval": 18} as MyCustomCSS}/>   
              <span style={{"--interval": 21} as MyCustomCSS}/>   
              <span style={{"--interval": 15} as MyCustomCSS}/>   
              <span style={{"--interval": 13} as MyCustomCSS}/>   
              <span style={{"--interval": 26} as MyCustomCSS}/>   
              <span style={{"--interval": 17} as MyCustomCSS}/>   
              <span style={{"--interval": 13} as MyCustomCSS}/>   
              <span style={{"--interval": 28} as MyCustomCSS}/>   
              <span style={{"--interval": 30} as MyCustomCSS}/>   
              <span style={{"--interval": 11} as MyCustomCSS}/>   
              <span style={{"--interval": 12} as MyCustomCSS}/>   
              <span style={{"--interval": 24} as MyCustomCSS}/>   
              <span style={{"--interval": 10} as MyCustomCSS}/>   
              <span style={{"--interval": 14} as MyCustomCSS}/>   
              <span style={{"--interval": 23} as MyCustomCSS}/>   
              <span style={{"--interval": 18} as MyCustomCSS}/>   
              <span style={{"--interval": 16} as MyCustomCSS}/>   
              <span style={{"--interval": 19} as MyCustomCSS}/>   
              <span style={{"--interval": 19} as MyCustomCSS}/>   
              <span style={{"--interval": 20} as MyCustomCSS}/>   
              <span style={{"--interval": 22} as MyCustomCSS}/>   
              <span style={{"--interval": 25} as MyCustomCSS}/>   
              <span style={{"--interval": 18} as MyCustomCSS}/>   
              <span style={{"--interval": 21} as MyCustomCSS}/>   
              <span style={{"--interval": 15} as MyCustomCSS}/>   
              <span style={{"--interval": 13} as MyCustomCSS}/>   
              <span style={{"--interval": 26} as MyCustomCSS}/>   
              <span style={{"--interval": 17} as MyCustomCSS}/>   
              <span style={{"--interval": 13} as MyCustomCSS}/>   
              <span style={{"--interval": 28} as MyCustomCSS}/>   
              <span style={{"--interval": 30} as MyCustomCSS}/>   
              <span style={{"--interval": 11} as MyCustomCSS}/>   
              <span style={{"--interval": 12} as MyCustomCSS}/>   
              <span style={{"--interval": 24} as MyCustomCSS}/>   
              <span style={{"--interval": 10} as MyCustomCSS}/>   
              <span style={{"--interval": 14} as MyCustomCSS}/>   
              <span style={{"--interval": 23} as MyCustomCSS}/>   
              <span style={{"--interval": 18} as MyCustomCSS}/>   
              <span style={{"--interval": 16} as MyCustomCSS}/>   
              <span style={{"--interval": 19} as MyCustomCSS}/>   
              <span style={{"--interval": 19} as MyCustomCSS}/>   
              <span style={{"--interval": 20} as MyCustomCSS}/>   
              <span style={{"--interval": 22} as MyCustomCSS}/>   
              <span style={{"--interval": 25} as MyCustomCSS}/>   
              <span style={{"--interval": 18} as MyCustomCSS}/>   
              <span style={{"--interval": 21} as MyCustomCSS}/>   
              <span style={{"--interval": 15} as MyCustomCSS}/>   
              <span style={{"--interval": 13} as MyCustomCSS}/>   
              <span style={{"--interval": 26} as MyCustomCSS}/>   
              <span style={{"--interval": 17} as MyCustomCSS}/>   
              <span style={{"--interval": 13} as MyCustomCSS}/>   
              <span style={{"--interval": 28} as MyCustomCSS}/>   
              <span style={{"--interval": 30} as MyCustomCSS}/>   
              
          </div>
        {children}
        </div>
        </body>
    </html>
  )
}
